In [116]:
import numpy as np

In [117]:
#Question 1(a)

def calculate_BMI( weight, height):
    bmi = weight / (height* height)
    if bmi >= 30:
        return "Obesity"
    elif 18.5 <= bmi < 24.9:
        return "Normal weight"
    elif 25 <= bmi < 29.9:
        return "Overweight"
    else:
        return "Underweight"

print(calculate_BMI(50,1.6))

Normal weight


In [118]:
matric_no = "MAT20231234"

print(matric_no[3:7])
print(matric_no.startswith("MAT"))

def generate_matric_number(fac, year, student_id) :
    #return f"{fac}{year}{student_id}"
    print(str(fac) + str(year) + str(student_id))

generate_matric_number(fac="FC", year=2025, student_id=8899)

2023
True
FC20258899


In [119]:
story="Once upon a time, in a land far away, there lived a young programmer who loved to solve problems. He spent his days learning Python and exploring the secrets of code."

print("Length: ", len(story))
print("First occurrence: ", story.find('Python'))
print("Extract substring: ", story[5:16])

start = story.find('there')
end = story.find('problems') + 8
print(story[start:end])
print("Reversed string: ", story[::-1])

Length:  166
First occurrence:  125
Extract substring:  upon a time
there lived a young programmer who loved to solve problems
Reversed string:  .edoc fo sterces eht gnirolpxe dna nohtyP gninrael syad sih tneps eH .smelborp evlos ot devol ohw remmargorp gnuoy a devil ereht ,yawa raf dnal a ni ,emit a nopu ecnO


In [120]:
#Question 1(d)
average=  lambda a,b,c : (a+b+c)/3

print(average(10,20,30))

20.0


In [121]:
data =((1,"Alice",25),(2,"Bob",30),(3,"Charlie",35))
data

print(data[2])

print(len(data))

id, name, age = data[1]
print(id)
print(name)
print(age)

list1=[1,2,3,4]
list2=[5,6,7,8]
concatenate= list1+list2
print(concatenate)
concatenate.append(9)
print(concatenate)


(3, 'Charlie', 35)
3
2
Bob
30
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [122]:
import numpy as np

random_num = np.random.randint(1,101, size = 30)
random_num

array([  3, 100,  64,  82,  14,   7,  41,  24,  69,  94,  96,  87,  61,
        40,  51,  44,  84,   4,  80,  59,  36,  74,  60,  60,   4,  92,
        24,  44,  95,  75])

In [152]:
arr= random_num.reshape(5,6)
print(arr)


[[  3 100  64  82  14   7]
 [ 41  24  69  94  96  87]
 [ 61  40  51  44  84   4]
 [ 80  59  36  74  60  60]
 [  4  92  24  44  95  75]]


In [164]:
col3 = arr[:, 2]
print("Column 3:", col3)

Column 3: [64 69 51 36 24]


In [166]:
col4 = arr[:, 3]
sum_col4 = np.sum(col4)
print("Sum of Column 4:", sum_col4)

Sum of Column 4: 338


In [168]:
sum_col3_col4 = col3 + col4
print("Sum of Col3 and Col4 (element-wise):", sum_col3_col4)


Sum of Col3 and Col4 (element-wise): [146 163  95 110  68]


In [172]:
print("Matrix:\n", arr)
print()
print("Column 3:", col3)
print("Column 4:", col4)
print("Sum of Column 4:", sum_col4)
print("Element-wise sum of Col3 and Col4:", sum_col3_col4)


Matrix:
 [[  3 100  64  82  14   7]
 [ 41  24  69  94  96  87]
 [ 61  40  51  44  84   4]
 [ 80  59  36  74  60  60]
 [  4  92  24  44  95  75]]

Column 3: [64 69 51 36 24]
Column 4: [82 94 44 74 44]
Sum of Column 4: 338
Element-wise sum of Col3 and Col4: [146 163  95 110  68]


In [176]:
arr = np.random.randint (10,51, size =(5,4))
arr


array([[40, 46, 31, 38],
       [12, 17, 46, 19],
       [20, 48, 47, 46],
       [29, 48, 34, 27],
       [21, 41, 49, 32]])

In [194]:
arr.sort(axis = 1)
print(arr)

# pick 1

sorted_array = np.sort(arr, axis =1)
print("Sorted array (each row):\n", sorted_array)


[[12 17 19 31]
 [20 27 34 41]
 [21 32 46 46]
 [29 38 47 48]
 [40 46 48 49]]
Sorted array (each row):
 [[12 17 19 31]
 [20 27 34 41]
 [21 32 46 46]
 [29 38 47 48]
 [40 46 48 49]]


In [208]:
arr.sum(axis =0)

array([122, 160, 194, 215])

In [210]:
maximum_value = np.max(arr)
print("Maximum value in the array:", maximum_value)


Maximum value in the array: 49
